cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - JENKINS_HOME=true
  - secure: F4uKO8PZ94lMrhWvKU+0NxiXE0CwD+5N3rhoptsj+Dl+4ktrysBr+z8MC40BR/lV1HkaNtnOv2VMDf3xV0v6RzLflC/MALmMDmVzuMEWQcJ52Da73Gz2JcBb8o3UU3Ph1KlKxKHsTPKeo08H0TsCkVh9v9bHGsSeSYXUSV4OSOVZkPJ+IIi/eoFWa77lXzZ7LVASmufgv7XYDOYjZLhPbWYmktiFh8BQQn8hRV5L0Y6r6I82KFalq8nUXUba2EOrfbbZXfiJ5TWP6Lnjz9QABhKFepffX0D173GDjeVlkSXQf14769+npoFV5XrwUDKtPfh4HIC3pvlgVcCSQurl/IlKGisyVFRKTCBg0WYqHMVSn2/ltv5pURJonefnwbox6Atd5fzfleWvyPtPnf/Q4o5VU07gvpj4ejCYu+gWJ2RtSXwIS+NYxkZL5vnT8ZbQMiYqEOnq36fCXhGzYA//BAKocHoIWXs2IclrEnkg+SRgDD6A3+t4BWYKt9tJZioHowdGjbvtQCqDrDM2HlWf92CUNR6aUrRcDzRY12Q48z61V3iYhX7zAy9FWH/5exWP3FcKadsP8eyeFzXGN01+ep6zkc3dyuIADHEoDEO25utui508CsbhdQbrlH3JOqU/+e+2aUO8FtC8mL59X8j7L+PHnp1W/nUycmm60z2p/dg=
language: java
jdk:
- openjdk8
branches:
  only:
  - master
before_install:
- echo "MAVEN_OPTS='-Xmx256m'" > ~/.mavenrc
- curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/dangernoodle-io/dangernoodle-io-build-pom/master/src/main/travis/settings.xml
install: true
script:
- mvn -B -V verify jacoco:report
notifications:
  email: false
  slack:
    rooms:
      secure: pBYLGOSjdg+mz7UzzImN+QyK8DEoYk+Ws7G7xyBVNQDeC4bnoAmqW4UU1LZt+Q2jAVIBmjWgITwgtfPEN9q8uOJE3MER6Y9rC18e/03Et9P8sYbNeOS8PnvCo96cxGip7XvjzlT9eznQU/pn6F65cqP6yb1aCjmnmnKHlm85XESXoqbXhS8ZZecd+mmVQG5nMZe2kWstlYjKX3smdn0qSrjm6mA6bKdtDZN4FON06EA0OTwPAmFVbHfmLaFdrEkRvNmOKhLTiK02v1MGfKZw6k+dOM4vXkKlITp0F9jatvZ5Y+eGLUn9ZL1DnSTj9+rpqo/z2DkddZQiOd+CBE2IGXp4PusVIkDfQ7EsGnEkjgHt7AtppCCM1V65UgoG1Zywq9KhuEE42EKuS03VagORCisGjaPvWXvtTjCC0YIauyp96FVsfpokXvf+oiuxy98ZP5M6LYrzmz/V2yhIkNFXKow9/eY0b1DsUOsA78uQu78tekqyx27wRepAmDyuP5sdMf10Q/50zgov5rIJzLt9WX2gPutnZYpua8OtUoBAvRY9YC9dfZsCBqcRT60876+vJAed11oFMHE5F99USaNyF41cGkbqrdSps41LsjV38ct/vJ/vqMyQ0k2EPsdsh6z5RoQ17iex3go9jwMBnEO407Ly/1qizY1QQUquoYKgD9U=
